Hydrator not acception DateTime objects on @ODM\Date fields
~~

Exception: DateTime::__construct() expects parameter 1 to be string, object given
tests\Hydrators\DoctrineODMMongoDBTestsHydrationClosureUserHydrator.php:49
lib\Doctrine\ODM\MongoDB\Hydrator\HydratorFactory.php:428
tests\Doctrine\ODM\MongoDB\Tests\HydratorTest.php:31